# Generated by Django 4.1.3 on 2023-03-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userloginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
